-- CreateEnum for UserRole
CREATE TYPE "UserRole" AS ENUM ('ADMIN', 'MANAGER', 'TECHNICIAN', 'CLIENT', 'VIEWER');

-- CreateEnum for Maintenance
CREATE TYPE "MaintenanceType" AS ENUM ('PREVENTIVE', 'CORRECTIVE', 'WARRANTY', 'CLEANING');
CREATE TYPE "MaintenancePriority" AS ENUM ('SCHEDULED', 'URGENT');
CREATE TYPE "MaintenanceStatus" AS ENUM ('PENDING_APPROVAL', 'SCHEDULED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED');

-- AlterTable users - change role to enum
ALTER TABLE "users" ALTER COLUMN "role" DROP DEFAULT;
ALTER TABLE "users" ALTER COLUMN "role" TYPE "UserRole" USING (
  CASE
    WHEN "role" = 'ADMIN' THEN 'ADMIN'::"UserRole"
    WHEN "role" = 'MANAGER' THEN 'MANAGER'::"UserRole"
    WHEN "role" = 'TECHNICIAN' THEN 'TECHNICIAN'::"UserRole"
    WHEN "role" = 'VIEWER' THEN 'VIEWER'::"UserRole"
    ELSE 'CLIENT'::"UserRole"
  END
);
ALTER TABLE "users" ALTER COLUMN "role" SET DEFAULT 'CLIENT'::"UserRole";

-- AlterTable maintenance_records - add new fields
ALTER TABLE "maintenance_records"
  ADD COLUMN "type" "MaintenanceType",
  ADD COLUMN "priority" "MaintenancePriority" DEFAULT 'SCHEDULED'::"MaintenancePriority",
  ADD COLUMN "status_new" "MaintenanceStatus" DEFAULT 'PENDING_APPROVAL'::"MaintenanceStatus",
  ADD COLUMN "requestedDate" TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN "startedDate" TIMESTAMP(3),
  ADD COLUMN "title" TEXT,
  ADD COLUMN "privateNotes" TEXT,
  ADD COLUMN "autoGenerated" BOOLEAN DEFAULT false;

-- Migrate existing maintenanceType to new type enum
UPDATE "maintenance_records" SET "type" =
  CASE
    WHEN "maintenanceType" = 'PREVENTIVE' THEN 'PREVENTIVE'::"MaintenanceType"
    WHEN "maintenanceType" = 'CORRECTIVE' THEN 'CORRECTIVE'::"MaintenanceType"
    WHEN "maintenanceType" = 'WARRANTY' THEN 'WARRANTY'::"MaintenanceType"
    WHEN "maintenanceType" = 'CLEANING' THEN 'CLEANING'::"MaintenanceType"
    ELSE 'PREVENTIVE'::"MaintenanceType"
  END;

-- Migrate existing status to new status enum
UPDATE "maintenance_records" SET "status_new" =
  CASE
    WHEN "status" = 'SCHEDULED' THEN 'SCHEDULED'::"MaintenanceStatus"
    WHEN "status" = 'IN_PROGRESS' THEN 'IN_PROGRESS'::"MaintenanceStatus"
    WHEN "status" = 'COMPLETED' THEN 'COMPLETED'::"MaintenanceStatus"
    WHEN "status" = 'CANCELLED' THEN 'CANCELLED'::"MaintenanceStatus"
    ELSE 'SCHEDULED'::"MaintenanceStatus"
  END;

-- Set title from description if exists
UPDATE "maintenance_records" SET "title" = COALESCE(LEFT("description", 100), 'Mantenimiento');

-- Make new fields NOT NULL after data migration
ALTER TABLE "maintenance_records"
  ALTER COLUMN "type" SET NOT NULL,
  ALTER COLUMN "title" SET NOT NULL;

-- Drop old columns
ALTER TABLE "maintenance_records"
  DROP COLUMN "maintenanceType",
  DROP COLUMN "status";

-- Rename status_new to status
ALTER TABLE "maintenance_records" RENAME COLUMN "status_new" TO "status";

-- CreateTable MaintenanceTechnician
CREATE TABLE "maintenance_technicians" (
    "id" TEXT NOT NULL,
    "maintenanceId" TEXT NOT NULL,
    "technicianId" TEXT NOT NULL,
    "role" TEXT,
    "assignedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "maintenance_technicians_pkey" PRIMARY KEY ("id")
);

-- CreateTable MaintenancePart
CREATE TABLE "maintenance_parts" (
    "id" TEXT NOT NULL,
    "maintenanceId" TEXT NOT NULL,
    "inventoryItemId" TEXT NOT NULL,
    "quantity" INTEGER NOT NULL,
    "notes" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "maintenance_parts_pkey" PRIMARY KEY ("id")
);

-- CreateTable MaintenanceStatusHistory
CREATE TABLE "maintenance_status_history" (
    "id" TEXT NOT NULL,
    "maintenanceId" TEXT NOT NULL,
    "status" "MaintenanceStatus" NOT NULL,
    "notes" TEXT,
    "changedById" TEXT NOT NULL,
    "changedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "maintenance_status_history_pkey" PRIMARY KEY ("id")
);

-- CreateTable MaintenanceConfig
CREATE TABLE "maintenance_configs" (
    "id" TEXT NOT NULL,
    "equipmentType" TEXT NOT NULL,
    "intervalDays" INTEGER NOT NULL,
    "notifyDaysBefore" INTEGER NOT NULL,
    "autoSchedule" BOOLEAN NOT NULL DEFAULT true,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "maintenance_configs_pkey" PRIMARY KEY ("id")
);

-- CreateTable Notification
CREATE TABLE "notifications" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "type" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "message" TEXT NOT NULL,
    "data" JSONB,
    "read" BOOLEAN NOT NULL DEFAULT false,
    "readAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "notifications_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "maintenance_technicians_maintenanceId_technicianId_key" ON "maintenance_technicians"("maintenanceId", "technicianId");

-- CreateIndex
CREATE UNIQUE INDEX "maintenance_configs_equipmentType_key" ON "maintenance_configs"("equipmentType");

-- CreateIndex
CREATE INDEX "notifications_userId_read_idx" ON "notifications"("userId", "read");

-- CreateIndex
CREATE INDEX "notifications_createdAt_idx" ON "notifications"("createdAt");

-- AddForeignKey
ALTER TABLE "maintenance_technicians" ADD CONSTRAINT "maintenance_technicians_maintenanceId_fkey" FOREIGN KEY ("maintenanceId") REFERENCES "maintenance_records"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "maintenance_technicians" ADD CONSTRAINT "maintenance_technicians_technicianId_fkey" FOREIGN KEY ("technicianId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "maintenance_parts" ADD CONSTRAINT "maintenance_parts_maintenanceId_fkey" FOREIGN KEY ("maintenanceId") REFERENCES "maintenance_records"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "maintenance_parts" ADD CONSTRAINT "maintenance_parts_inventoryItemId_fkey" FOREIGN KEY ("inventoryItemId") REFERENCES "inventory_items"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "maintenance_status_history" ADD CONSTRAINT "maintenance_status_history_maintenanceId_fkey" FOREIGN KEY ("maintenanceId") REFERENCES "maintenance_records"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "maintenance_status_history" ADD CONSTRAINT "maintenance_status_history_changedById_fkey" FOREIGN KEY ("changedById") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "notifications" ADD CONSTRAINT "notifications_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- Insert default maintenance configs
INSERT INTO "maintenance_configs" ("id", "equipmentType", "intervalDays", "notifyDaysBefore", "autoSchedule", "isActive", "createdAt", "updatedAt")
VALUES
  (gen_random_uuid()::text, 'solar_panels', 90, 7, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'solar_heater', 90, 7, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'general', 90, 7, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
